# render.yaml
services:
  - type: web
    runtime: static
    name: webos-static
    buildCommand: npm ci && npm run build   # runs `next build` → writes to `out/`
    staticPublishPath: out
    previews:
      generation: automatic
    envVars:
      - key: NODE_VERSION
        value: 22
